env:
  global:
    - CC_TEST_REPORTER_ID=381ae88192485c389abc63a1c89ec88b7e22bee2534130bf4b3333a007ea6e76
language: node_js
node_js:
  - "stable"
script:
- npm test

env:
- NODE_ENV=test

before_script:
  - psql -c 'create database event_manager_test;' -U postgres
  - npm install nyc coveralls codeclimate-test-reporter -g

after_script:
  - nyc report --reporter=text-lcov | coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info

services:
  - postgresql

addons:
  postgresql: "9.6"
